MAGIC = "vrata123"

NICK_TYPE = "nick"
LOBBY_INFO = "lbin"
MESSAGE_TYPE_LENGTH = 4
MESSAGE_LENGTH_FORMAT = 3

LOBBY_INFO_TYPE = "lbin"
JOIN_TYPE = "join"
LOBBY_JOIN_RESPONSE = "lbjn"
CAN_GAME_START = "cngs"
START_THE_GAME = "play"
GAME_STARTED_INIT = "gmst"